---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "grapple-init"
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grapple-init-cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: grapple-init
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: grapple-init-v022
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: grapple-init
          image: grpl/grapple-cli:0.2.36
          command: ["/bin/bash","-c"]
          args: ["grpl cluster install --params --TARGET_PLATFORM=CIVO --CIVO_REGION=${CIVO_REGION} --CIVO_CLUSTER=${CIVO_CLUSTER_NAME} --CIVO_EMAIL_ADDRESS=${CIVO_EMAIL_ADDRESS} --GRAPPLE_VERSION=${VERSION} --AUTO_CONFIRM=true --CIVO_CLUSTER_ID=${CIVO_CLUSTER_ID} --CIVO_MASTER_IP=${CIVO_MASTER_IP} # && grpl example deploy "]
      restartPolicy: Never
      serviceAccountName: grapple-init
